from typing import Protocol, runtime_checkable


@runtime_checkable
class UserRepository(Protocol):
    """用户数据访问协议"""
    async def get_by_id(self, user_id: str) -> dict | None: ...
    async def get_by_email(self, email: str) -> dict | None: ...
    async def create(self, email: str, password_hash: str, name: str) -> dict: ...
    async def update(self, user_id: str, **kwargs) -> None: ...


@runtime_checkable
class ProjectRepository(Protocol):
    """项目数据访问协议"""
    async def create(
        self, user_id: str, name: str, total_budget: float, **kwargs
    ) -> dict: ...
    
    async def get_by_id(self, project_id: str) -> dict | None: ...
    
    async def list_by_user(
        self, user_id: str, status: str | None = None, limit: int = 20
    ) -> list[dict]: ...
    
    async def update(self, project_id: str, **kwargs) -> None: ...
    
    async def update_spent(self, project_id: str, amount: float) -> None: ...
    
    async def delete(self, project_id: str) -> None: ...


@runtime_checkable
class ChatRepository(Protocol):
    async def create_session(self, user_id: str, game_info: dict) -> str: ...
    async def add_message(self, session_id: str, role: str, content: str, metadata: dict | None = None) -> None: ...
    async def get_session(self, session_id: str) -> dict | None: ...
    async def list_sessions(self, user_id: str, limit: int = 20) -> list[dict]: ...


@runtime_checkable
class MaterialRepository(Protocol):
    """素材数据访问协议"""
    async def create(
        self, user_id: str, name: str, type: str, url: str, **kwargs
    ) -> dict: ...
    
    async def get_by_id(self, material_id: str) -> dict | None: ...
    
    async def list_by_user(
        self, user_id: str, type: str | None = None, limit: int = 50
    ) -> list[dict]: ...
    
    async def list_by_project(
        self, project_id: str, limit: int = 50
    ) -> list[dict]: ...
    
    async def list_by_campaign(
        self, campaign_id: str, limit: int = 50
    ) -> list[dict]: ...
    
    async def add_to_project(self, material_id: str, project_id: str) -> None: ...
    
    async def remove_from_project(self, material_id: str, project_id: str) -> None: ...
    
    async def add_to_campaign(self, material_id: str, campaign_id: str) -> None: ...
    
    async def remove_from_campaign(self, material_id: str, campaign_id: str) -> None: ...
    
    async def delete(self, material_id: str) -> None: ...


@runtime_checkable
class CampaignRepository(Protocol):
    """投放数据访问协议"""
    async def create(
        self, project_id: str, name: str, platform: str, budget: float, **kwargs
    ) -> dict: ...
    
    async def get_by_id(self, campaign_id: str) -> dict | None: ...
    
    async def list_by_project(
        self, project_id: str, status: str | None = None, limit: int = 20
    ) -> list[dict]: ...
    
    async def update_status(self, campaign_id: str, status: str) -> None: ...
    
    async def update_spent(self, campaign_id: str, amount: float) -> None: ...
    
    async def add_material(self, campaign_id: str, material_id: str) -> None: ...
    
    async def remove_material(self, campaign_id: str, material_id: str) -> None: ...
    
    async def get_materials(self, campaign_id: str) -> list[dict]: ...
    
    async def delete(self, campaign_id: str) -> None: ...


@runtime_checkable
class MetricRepository(Protocol):
    async def get_latest(self, campaign_id: str) -> dict | None: ...
    async def get_timeseries(self, campaign_id: str, hours: int = 24) -> list[dict]: ...
