from typing import Protocol, runtime_checkable


@runtime_checkable
class ChatRepository(Protocol):
    async def create_session(self, user_id: str, game_info: dict) -> str: ...
    async def add_message(self, session_id: str, role: str, content: str, metadata: dict | None = None) -> None: ...
    async def get_session(self, session_id: str) -> dict | None: ...
    async def list_sessions(self, user_id: str, limit: int = 20) -> list[dict]: ...


@runtime_checkable
class MaterialRepository(Protocol):
    async def create_task(self, session_id: str, direction: str, user_id: str) -> str: ...
    async def get_task(self, task_id: str) -> dict | None: ...
    async def update_task(self, task_id: str, materials: list[dict], status: str) -> None: ...


@runtime_checkable
class CampaignRepository(Protocol):
    async def create(self, user_id: str, config: dict) -> str: ...
    async def get(self, campaign_id: str) -> dict | None: ...
    async def update_status(self, campaign_id: str, status: str) -> None: ...
    async def list_by_user(self, user_id: str, limit: int = 20) -> list[dict]: ...


@runtime_checkable
class MetricRepository(Protocol):
    async def get_latest(self, campaign_id: str) -> dict | None: ...
    async def get_timeseries(self, campaign_id: str, hours: int = 24) -> list[dict]: ...
