"""add contact_info table

Revision ID: bc612867f29f
Revises: 5c4d96eac377
Create Date: 2026-06-02 15:17:17.997826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc612867f29f'
down_revision: Union[str, None] = '5c4d96eac377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_info_created_at'), 'contact_info', ['created_at'], unique=False)
    op.create_index(op.f('ix_contact_info_status'), 'contact_info', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_info_status'), table_name='contact_info')
    op.drop_index(op.f('ix_contact_info_created_at'), table_name='contact_info')
    op.drop_table('contact_info')
    # ### end Alembic commands ###
